### PR TITLE
Update READMEtemplate.md with Structured README reference

### PR DESCRIPTION
**Pull request by shaloo**
### Description

Based on @fokusferit suggestion,   here is a request for adding a reference to 'Structured README'.  I'm open to suggestions, in case there is a better way for integration.

### Related Issue
None
### Motivation and Context
Please see discussion on the same as part of updating Mahout README at feedmereadmes here https://github.com/LappleApple/feedmereadmes/issues/12 

### How Has This Been Tested?
Preview checked during merge

### Screenshots (if appropriate):
NA

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by shaloo — COMMENTED** [review]
@LappleApple : Pls review

**Comment by lasomethingsomething** [comment]
LGTM, thanks!

**Comment by shaloo** [comment]
Gr8, thanks!  I'll delete patch branch right away.

**Comment by lasomethingsomething** [comment]
Nice work on the Structured README. I edited your PR a bit, fwiw.

**Pull request merged**
